# --- Central-V specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 10
batch_size_run: 10
batch_size: 10

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval_or_tau: 200

lr: 0.0005
critic_lr: 0.0005


agent_output_type: "pi_logits"
learner: "actor_critic_learner"
entropy_coef: 0.01

q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic"

name: "maa2c"
