# --- MADDPG specific parameters ---

runner: "episode"

buffer_size: 50000
# update the target network every {} episodes
target_update_interval_or_tau: 0.01



# use the madddpg_learner to train
mac: "maddpg_mac"
reg: 0.001
batch_size: 16
lr: 0.0005

learner: "maddpg_learner"
agent_output_type: "pi_logits"
hidden_dim: 128
rnn_hidden_dim: 128
critic_type: "maddpg_critic"
name: "maddpg"
